#!/usr/bin/env bash
#Bash script that installs HAProxy & makes configurations

apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 6052-webs
    bind *:80
    mode http
    balance roundrobin
    server 5981-web-01 44.222.224.12:80 check
    server 5981-web-02 52.91.5.4:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
